/* Generated By:JavaCC: Do not edit this line. MiniJavaParserTreeConstants.java Version 6.0_beta */
package parser;

public interface MiniJavaParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTCLASSDECL = 2;
  public int JJTVARDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTFORMALLIST = 5;
  public int JJTFORMALREST = 6;
  public int JJTTYPE = 7;
  public int JJTSTMT = 8;
  public int JJTEXP = 9;
  public int JJTEXPPRIM = 10;
  public int JJTOP = 11;
  public int JJTEXPLIST = 12;
  public int JJTEXPREST = 13;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "ClassDecl",
    "VarDecl",
    "MethodDecl",
    "FormalList",
    "FormalRest",
    "Type",
    "Stmt",
    "Exp",
    "ExpPrim",
    "Op",
    "ExpList",
    "ExpRest",
  };
}
/* JavaCC - OriginalChecksum=b4b2636c238b382cf0dd3a49e6f31455 (do not edit this line) */
