/* Generated By:JavaCC: Do not edit this line. MiniJavaParserVisitor.java Version 5.0 */
package parser;

public interface MiniJavaParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTMainClass node, Object data);
  public Object visit(ASTClassDecl node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTMethodDecl node, Object data);
  public Object visit(ASTFormalList node, Object data);
  public Object visit(ASTFormalRest node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTStmt node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTExpPrim node, Object data);
  public Object visit(ASTOp node, Object data);
  public Object visit(ASTExpList node, Object data);
  public Object visit(ASTExpRest node, Object data);
}
/* JavaCC - OriginalChecksum=b0ab05ca1381f5f0a56d4f188dbf9f15 (do not edit this line) */
