#! /bin/sh

compdir="$1"

if [ ! -d "$compdir" ]
  then
    echo "error: compiler directory \"$compdir\" not found."
    echo usage: $0 [COMPILER-SOURCE-DIR]
    exit 1
  fi

cd $compdir

if [ -f build.xml ] && [ -f DESC ] && [ -d src ] && [ -d lib ] && [ -f report.pdf ]
  then true
  else
    echo "error: missing files in \"$compdir\"."
    exit
  fi

if [ ! -s report.pdf ]
  then
    echo "NOTE: Empty report.pdf--need to resubmit before oral presentation"
  fi

if uuencode x </dev/null >/dev/null
  then true
  else
    echo "error: The program \"uuencode\" is missing."
    echo "       Please install GNU package sharutils."
    exit 1
  fi

#cd ..
#tar cf - `basename $compdir` | gzip | uuencode x | mailx -s '' submit@tigris.csc.kth.se

# Modification to only send the necessary files
TEMPDIR="tigris-submit-temp"
mkdir "$HOME/$TEMPDIR"
cp -r "$compdir/lib" "$HOME/$TEMPDIR/lib"
cp -r "$compdir/src" "$HOME/$TEMPDIR/src"
cp  "$compdir/build.xml" "$HOME/$TEMPDIR"
cp  "$compdir/DESC" "$HOME/$TEMPDIR"
cp  "$compdir/report.pdf" "$HOME/$TEMPDIR"

cd $HOME
tar cf - `basename $TEMPDIR` | gzip | uuencode x | mailx -s '' submit@tigris.csc.kth.se
rm -f -r "$TEMPDIR" # Remove the temporary directory

exit 0
